config/routes.rb
Rails.application.routes.draw do


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#delete'

  get 'reports/jobs_all' => 'reports#jobs_all'
  get 'photos/:id/check' => 'photos#check'
  get 'works' => 'stores#user'
  put '/events/readall' => 'events#readall'

  #get 'admin/index/task1' => 'admin/#task1'
  #root :to => 'stores#index'
  root :to => 'stores#main'


  resources :user do
    resources :jobs
    resources :events
  end
  resources :stores, param: :code do
    resources :jobs do
      resources :patch_panels do
        resources :ports
      end
      resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
      resources :registrators
    end
  end

  resources :jobs do
    member do
      put 'done'
      put 'accept'
      put 'return_to_work'
      put 'before_done_send_to_admin'
      put 'sn_inc_create'
      put 'sn_inc_delete_link'
      put 'sn_task_create'
      put 'calculate_latest_job_in_store'
      put 'calculate_latest_job_in_store_all'
    end
    resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
    resources :patch_panels do
      resources :ports
    end
    resources :registrators
  end


  namespace :admin do
    get 'index' => 'admin#index'
    resources :staffs
    resources :users
    resources :groupmanager
    resources :settings_ldap
  end

  namespace :info do
    root :to => 'info#index'
    get 'index' => 'info#index'
    get 'category/add' => 'category#add'
    get 'subcategory/add' => 'subcategory#add'
    get 'file/add' => 'file#add'

    get 'category/edit' => 'category#edit'
    get 'subcategory/edit' => 'subcategory#edit'
    get 'file/edit' => 'file#edit'
    get 'file/about' => 'file#about'

    resources :category
    resources :subcategory
    resources :file
  end


    resources :reports
  resources :staff, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/info/category_controller.rb
module Info
  class Info::CategoryController < ApplicationController

    before_action :set_category, only: [:index, :show, :destroy, :edit, :update]

  def index
    @categories=Infodb.where(base_type:1)
    @category_active=@category.id
    @subcategories=Infodb.where(category_id:@category.id,base_type:2)
    render('index')
  end

  def getcount;
    Infodb.where(base_type:1).count
  end

  def show
    index
  end

  def add
    @category=nil

    respond_to do |format|
      format.js
    end
  end

  def create
        tempparams=params.permit(:id,:name,:desc)
    data = {}  
    data[:base_type]=1
    data[:category_id]=0
    data[:subcategory_id]=0
    data[:created_by]=current_user.id    
    tempparams=tempparams.merge( data )
    @category = Infodb.new(tempparams)
       if @category.save
           respond_to do |format|
        format.js
      end
      redirect_to info_index_path, success: "Категория успешно добавлена"
    else
      redirect_back fallback_location: :back, danger: params[:name]
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    tempparams=params.require(:infodb).permit(:id,:name,:desc)
    data = {}
    data[:updated_by]=current_user.id
    tempparams=tempparams.merge( data )

    if @category.update(tempparams)
      respond_to do |format|
        format.js
      end
      redirect_to info_index_path, success: "Категория обновлена"
    else
      redirect_to info_index_path, danger: "Нет категории с таким id [при запросе категории]"
    end

  end


  def is_empty
    Infodb.where(category_id:@category.id).count<1
  end

  def destroy

    cat_temp=@category

    if not is_empty
      redirect_to info_category_path(@category.id), danger: "Категория #{cat_temp.name} имеет вложения, сперва необходимо удалить их"
      return
    end

    if @category.destroy
      redirect_to info_index_path, success: "Категория #{cat_temp.name} успешно удалена"
    end
  end

  def info_params
    params.require(:infodb).permit(:id,:name,:desc,:base_type,:source_url,:category_id,:subcategory_id,:created_by)
  end

  def set_category
    begin
      @category = Infodb.find(params[:id])
    rescue
      redirect_to info_index_path, danger: "Нет категории с таким id [при запросе категории]"
    end

  end

  def docs
    @info = Info.all 
  end

  def docs_add_subcat;
    respond_to do |format|
      format.js
      format.html
    end
  end

  def docs_subcat_create
    @docs = Info.new(info_params)

    if @docs.save
      respond_to do |format|    
        format.js
      end
    end

  end

  def docs_subcat_update
    @docs = Info.find(params[:id])
    if @docs.save
      respond_to do |format|       
        format.js
      end
    end
  end

  def docs_add_subcat_file;
    respond_to do |format|
      format.js
      format.html
    end
  end

  def docs_subcat_file_create
    @docs = Info.new(info_params)

    if @docs.save
      respond_to do |format|      
        format.js
      end
    end

  end

  def docs_subcat_file_update
    @docs = Info.find(params[:id])
    if @docs.save
      respond_to do |format|
            format.js
      end
    end
  end
  def help
  end
  end
end

app/controllers/info/file_controller.rb
module Info
  class Info::FileController < ApplicationController

    before_action :set_category, only: [ :add, :index, :show, :destroy, :edit, :about]
    before_action :set_subcategory, only: [ :add, :index, :show, :destroy, :edit, :about]
    before_action :set_file, only: [ :index, :show, :destroy, :edit, :update, :about]


    def index
    end

    def show
    end

    def add
      @category_active=@category.id
      @subcategory_active=@subcategory.id
      respond_to do |format|
        format.js
      end
    end

    def create
      tempparams=params.permit(:id,:name,:desc,:source_url,:category_id,:subcategory_id,:filecustom)
      data = {}
      data[:base_type]=3
      data[:created_by]=current_user.id
      data[:updated_by]=current_user.id
      tempparams=tempparams.merge( data )

      @file = Infodb.new(tempparams)
      if @file.save
        respond_to do |format|
           format.js
        end
        redirect_to info_subcategory_path(@file.subcategory_id, :cid=>@file.category_id ), success: "Документ успешно добавлен"
      else
        clean_orphaned_blob
        redirect_back fallback_location: :back, danger: @file.errors.messages[:name].join(";")
      end
    end

    def edit
      respond_to do |format|
        format.js       
      end
    end

    def about
      @name_createdby=User.unscoped.search_by_id(@file.created_by)[0].name_short
      if @file.updated_by?
        @name_updatedby=User.unscoped.search_by_id(@file.updated_by)[0].name_short
      else
        @name_updatedby=@name_createdby
      end
      respond_to do |format|
        format.js       
      end
    end

    def update
      tempparams=params.require(:infodb).permit(:id,:name,:desc,:source_url,:filecustom)
      data = {} 
      data[:updated_by]=current_user.id
      tempparams=tempparams.merge( data )

      @file.filecustom.purge
      if @file.update(tempparams)
        respond_to do |format|
          format.js
        end
        redirect_to info_subcategory_path(@file.subcategory_id, :cid=>@file.category_id), success: "Документ обновлен"
      else
        clean_orphaned_blob
        redirect_to info_subcategory_path(@file.subcategory_id, :cid=>@file.category_id), danger: "Нет документа с таким id [при запросе документа] "+@file.errors.messages[:name].join(";")
      end

    end

    def destroy
      file_temp=@file
      @file.filecustom.purge
      if @file.destroy
        redirect_to info_subcategory_path(@subcategory.id, :cid=>@category.id), success: "Файл #{file_temp.name} успешно удалён"
      else
        clean_orphaned_blob
        redirect_back fallback_location: :back, danger: "Ошибка при удалении "
      end
    end

    def clean_orphaned_blob
      cnt=0
      errors=''
      ActiveStorage::Blob.where.not(id: ActiveStorage::Attachment.select(:blob_id)).find_each do |blob|
        blob.purge 

      end    
    end
    def info_params
      params.permit(:id,:name,:desc,:base_type,:source_url,:category_id,:subcategory_id,:created_by,:filecustom)
    end

    def set_file
      begin
        @file = Infodb.find(params[:id])
      rescue
        redirect_to info_index_path, danger: "Нет файла с таким id [при запросе файла]"
      end

    end
    def set_category
      begin
        @category = Infodb.find(params[:cid])
      rescue
        redirect_to info_index_path, danger: "Нет категории с таким id [при запросе файла]"
      end

    end

    def set_subcategory
      begin
        @subcategory = Infodb.find(params[:sid])
      rescue
        redirect_to info_index_path, danger: "Нет подкатегории с таким id [при запросе файла]"
      end
    end
  end
end

app/controllers/info/info_controller.rb
module Info
  class InfoController < ApplicationController

    def index;
      @categories=Infodb.where(base_type:1)
      render('index')
    end



  end
end

app/controllers/info/subcategory_controller.rb
module Info
  class Info::SubcategoryController < ApplicationController

    before_action :set_category, only: [:add, :index, :show, :destroy, :edit]
    before_action :set_subcategory, only: [:index, :show, :destroy, :edit, :update]
    
    def index
      @categories=Infodb.where(base_type:1)
      @category_active=@category.id

      @subcategories=Infodb.where(category_id:@category.id,base_type:2)
      @subcategory_active=@subcategory.id

      @files=Infodb.where(subcategory_id:@subcategory.id,base_type:3).order('name asc')

      tempparams=params.permit(:of)
      if tempparams.has_key?(:of) && !tempparams[:of].blank?
          @filetoshow=tempparams[:of]
      end

      render('index')
    end

    def show
      index
    end

    def add
      @category_active=@category.id

      respond_to do |format|
        format.js
        #format.html
      end
    end

    def create
      tempparams=params.permit(:id,:name,:desc,:category_id)


      # Проверяем, есть ли такая категория вообще, к которой будет привязана подкатегория
      if Infodb.where(params[:category_id]).count<1
        respond_to do |format|
          format.js
        end
        redirect_to request.referrer, danger: "Целевая категория не найдена (#{params[:category_id]})"
        return
      end

      #Дополняем данными
      data = {}
      data[:base_type]=2
      data[:subcategory_id]=0
      data[:created_by]=current_user.id
      tempparams=tempparams.merge( data )

      @subcategory = Infodb.new(tempparams)

      if @subcategory.save
        respond_to do |format|
          format.js
        end
        redirect_to info_category_path(@subcategory.category_id), success: "Подкатегория успешно добавлена"
      end
    end

    def edit
      #@category_active=@category.id
      respond_to do |format|
        format.js
        #format.html
      end
    end

    def update
      tempparams=params.require(:infodb).permit(:id,:name,:desc)
      data = {}  #= data = Hash.new
      data[:updated_by]=current_user.id
      tempparams=tempparams.merge( data )

      if @subcategory.update(tempparams)
        respond_to do |format|
          format.js
        end
        redirect_to info_category_path(@subcategory.category_id), success: "Подкатегория обновлена"
      else
        redirect_to info_index_path, danger: "Нет подкатегории с таким id [при запросе подкатегории]"
      end

    end

    def is_empty
      Infodb.where(subcategory_id:@subcategory.id,base_type:3).count<1
    end

    def destroy

      subcat_temp=@subcategory

      if not is_empty
        redirect_to info_subcategory_path(@subcategory.id, :cid=>@category.id), danger: "Подкатегория #{subcat_temp.name} имеет вложения, сперва необходимо удалить их"
        return
      end

      if @subcategory.destroy
        redirect_to info_category_path(@category.id), success: "Подкатегория #{subcat_temp.name} успешно удалена"
      end
    end

    def info_params
      params.permit(:id,:name,:desc,:base_type,:source_url,:category_id,:subcategory_id,:created_by,:of)
    end

    def set_category
      begin
        @category = Infodb.find(params[:cid])
      rescue
        redirect_to info_index_path, danger: "Нет категории с таким id [при запросе подкатегории]"
      end

    end

    def set_subcategory
      begin
        @subcategory = Infodb.find(params[:id])
      rescue
        redirect_to info_index_path, danger: "Нет подкатегории с таким id [при запросе подкатегории]"
      end

    end

  end

end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/category/_form_add.html.slim
div
  = form_with url: info_category_index_path, method: :post do |f|
    div.form-group
      = f.label :Название_категории
      = f.text_field :name, class: "form-control", placeholder: "Название", required: true
    div.form-group
      = f.label :Описание
      = f.text_area :desc, cols: "10", rows: "3", placeholder: "Необязательно", class: "form-control"
    div.form-group
      = f.submit value: "Сохранить", class: "btn btn-outline-primary", data: {disable_with: "Сохранение"}

app/views/info/category/_form_edit.html.slim
div
  = form_with model:@category, url: info_category_path(:id=>@category.id) do |f|
    /url: info_category_index_path, method: :put
    div.form-group
      = f.label :Название_категории
      = f.text_field :name, class: "form-control", placeholder: "Название", required: true
    div.form-group
      = f.label :Описание
      = f.text_area :desc, cols: "10", rows: "3", placeholder: "Описание", class: "form-control"
    div.form-group
      = f.submit value: "Сохранить", class: "btn btn-outline-primary", data: {disable_with: "Сохранение"}

app/views/info/category/_show.html.slim
- @active_cat= (@category_selected!=nil && @category_selected.id==category.id)
- @class_add=(@active_cat ? 'active' : '')
- @class_add2=(@active_cat ? 'glyphicon-chevron-down' : 'glyphicon-chevron-right')

div class="list-group-item d-flex justify-content-between align-items-center #{@class_add}"
  /i class="glyphicon #{@class_add2}"
  div
    -if category.name.empty?
      == category.name="<No name>"

    -if @active_cat
      = link_to category.name, info_category_path(category.id), style:"font-weight:bold", class:"alinkwhite"
    -else
      = link_to category.name, info_category_path(category.id), style:"font-weight:normal"


    /= link_to " x",  info_category_path(category.id), method: :delete, data: {confirm: "Удалить категорию?"} if current_user.admin?
    = link_to image_tag("menu/edit.png", style:'width:12px; margin-left:5px; vertical-align:middle; '), info_category_path(category.id), title:"Редактировать",
            "data-toggle":"modal", "data-target":"#exampleModal", "data-action":"edit_category","data-id":category.id  if current_user.admin?
    /= link_to image_tag("menu/edit.png", style: 'width:16px; vertical-align:middle; '), info_category_edit_path(:id=>category.id), title: "Редактировать" if current_user.admin?
  - @subcnt = Infodb.where(category_id:category.id,base_type:3).count
  - if @subcnt > 0
    span class="badge badge-primary badge-pill"
      = @subcnt

-if @active_cat
  div class="list-group" style="padding-bottom:10px"
    == render partial: '/info/subcategory/show', collection: @subcategories, as: :subcategory, cached: true, locals:{"@category_selected": @category}

    - if current_user.admin?
      div.list-group-item.text-right
        button.btn.btn-outline-secondary.bold data-toggle="modal" data-target="#exampleModal" data-action="add_subcategory" +

app/views/info/category/add.js.erb
$('h5[data-target="modal-title"]').html("Добавить новую категорию");
$('div[data-target="modal-body"]').html(`<%= render partial: 'info/category/form_add',locals: {"@category": @category} %>`)
$("#loading_image_modal").css('display','none');
$('div.btnModalDelete').html("");
//, locals: {"@docs": @docs}

app/views/info/category/create.js.erb
$('#exampleModal').modal('hide');
//location.replace('https://google.com');
//location.reload();

app/views/info/category/edit.js.erb
$('h5[data-target="modal-title"]').html("Изменить категорию <%= @category.name %>");
$('div[data-target="modal-body"]').html(`<%= render partial: 'info/category/form_edit',locals: {"@category": @category} %>`)
$("#loading_image_modal").css('display','none');
//, locals: {"@docs": @docs}

$('div.btnModalDelete').html(`<%= link_to image_tag("menu/bin2.png", style: 'width:26px; vertical-align:middle; margin:0px'),  info_category_path(@category.id), method: :delete, data: {confirm: "Удалить категорию?"} if current_user.admin? %>`)

app/views/info/category/index.html.slim
div.row.justify-content-center
  div.col style="max-width:400px"
    div class="list-group list-group-root well"
      == render partial: '/info/category/show', collection: @categories, as: :category, cached: true, locals:{"@category_selected": @category, "@subcategories":@subcategories}
      /== render partial: '/info/category/show', collection: @categories, as: :category, cached: true, locals:{"@category_selected": @category}

      - if current_user.admin?
        br
        br
        div.list-group-item.text-center
          button.btn.btn-outline-secondary data-toggle="modal" data-target="#exampleModal" data-action="add_category" Добавить категорию

  /div.col-3
    'Amount:
    '#{@categories.size}:#{@subcategories.size}
    == render partial: '/info/subcategory/show', collection: @subcategories, as: :subcategory, cached: true, locals:{"@category_selected": @category}

    - if current_user.admin?
      br
      br
      div
        button.btn.btn-outline-secondary data-toggle="modal" data-target="#exampleModal" data-action="add_subcategory" Добавить подкатегорию

  == render "info/modal"

    /div.nav.flex-column.nav-pills.sticky-top.rounded-lg.border style="top:5em" role="tablist" aria-orientation="vertical"
      /= link_to "Документы", info_docs_path, class: "nav-link #{'active' if action_name == 'docs'}"
      /= link_to "Помощь", info_help_path, class: "nav-link #{'active' if action_name == 'help'}"
  /div.col-3
    /== yield

css:

  .just-padding {
    padding: 15px;
  }

  .list-group.list-group-root {
    padding: 0;
    overflow: hidden;
  }

  .list-group.list-group-root .list-group {
    margin-bottom: 0;
  }

      .list-group.list-group-root .list-group-item {
    /* border-radius: 0;
    border-width: 1px 0 0 0; */
  }

      .list-group.list-group-root > .list-group-item:first-child {
    /* border-top-width: 0; */
  }

      .list-group.list-group-root > .list-group > .list-group-item {
    margin-left: 50px;
  }

      .list-group.list-group-root > .list-group > .list-group > .list-group-item {
        margin-left: 75px;
  }

  .alinkwhite {
    color: white
  }

  .alinkwhite:hover{
    color: white
  }

  .list-group-item.active {
    color: #404143;
    background-color: #404143;
    border-color: #9ca0a4;
  }


  .list-group-item {
    background-color: #fbfcfd;
  }


javascript:

    $('#exampleModal').on('show.bs.modal', function (event) {
        $event = $(event.relatedTarget).attr('data-action');
        modal_clear();
        modal_loading_show();
        switch ($event) {
            case "add_category":
                $.get(
                    "/info/category/add",
                    {format: "js"}
                );
                break;
            case "add_subcategory":
                $.get(
                    "/info/subcategory/add",
                    {format: "js", cid:#{@category_active}}
                );
                break;
            case "edit_category":
                $objId = $(event.relatedTarget).attr('data-id');
                $.get(
                    "/info/category/edit",
                    {format: "js", id: $objId}
                );
                break;
            case "edit_subcategory":
                $objID = $(event.relatedTarget).attr('data-id');
                $objCID = $(event.relatedTarget).attr('data-cid');
                $.get(
                    "/info/subcategory/edit",
                    {format: "js", id: $objID, cid: $objCID}
                );
                break;
        }
    });

app/views/info/category/update.js.erb
$('#exampleModal').modal('hide');
//location.replace('https://google.com');
//location.reload();