config/routes.rb
Rails.application.routes.draw do


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#delete'

  get 'reports/jobs_all' => 'reports#jobs_all'
  get 'photos/:id/check' => 'photos#check'
  get 'works' => 'stores#user'
  put '/events/readall' => 'events#readall'

  #get 'admin/index/task1' => 'admin/#task1'
  #root :to => 'stores#index'
  root :to => 'stores#main'


  resources :user do
    resources :jobs
    resources :events
  end
  resources :stores, param: :code do
    resources :jobs do
      resources :patch_panels do
        resources :ports
      end
      resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
      resources :registrators
    end
  end

  resources :jobs do
    member do
      put 'done'
      put 'accept'
      put 'return_to_work'
      put 'before_done_send_to_admin'
      put 'sn_inc_create'
      put 'sn_inc_delete_link'
      put 'sn_task_create'
      put 'calculate_latest_job_in_store'
      put 'calculate_latest_job_in_store_all'
    end
    resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
    resources :patch_panels do
      resources :ports
    end
    resources :registrators
  end


  namespace :admin do
    get 'index' => 'admin#index'
    resources :staffs
    resources :users
    resources :groupmanager
    resources :settings_ldap
  end

  namespace :info do
    root :to => 'info#index'
    get 'index' => 'info#index'
    get 'category/add' => 'category#add'
    get 'subcategory/add' => 'subcategory#add'
    get 'file/add' => 'file#add'

    get 'category/edit' => 'category#edit'
    get 'subcategory/edit' => 'subcategory#edit'
    get 'file/edit' => 'file#edit'
    get 'file/about' => 'file#about'

    resources :category
    resources :subcategory
    resources :file
  end


    resources :reports
  resources :staff, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  self.primary_key = :code
  default_scope { where("name NOT LIKE '%Ecomm%' AND name NOT LIKE '%TMALL%' AND baseidd IS NOT null AND (baseidd*1) > 1 ") }

  scope :by_name, ->(name) { where("name LIKE :name "+  # Произвольное имя магазина
                                       "or (baseidd*1) = :namefixed "+   #Точное совпадение по Номеру ROZN
                                       "or CONCAT('rozn',(baseidd*1)) LIKE :namefixed " + #Точное совпадение по roznНОМЕР
                                       "or (baseidd*1) = CONCAT(6,LPAD(:namefixed,GREATEST(LENGTH(:namefixed), 2),'0')) " + #Точное совпадение по Номеру ROZN, если он в формате 6xx
                                       "or CONCAT('rozn',(baseidd*1)) = CONCAT(6,LPAD(:namefixed,GREATEST(LENGTH(:namefixed), 2),'0')) ", #Точное совпадение по roznНОМЕР, если он в формате 6xx
                                        :name=>"%#{name}%",:namefixed=>"#{name}") }
  #scope :by_name, ->(name) { where("name LIKE (?) or (baseidd*1) = (?) or 'rozn'+(baseidd*1) LIKE (?)  ", "%#{name}%", "#{name}","#{name}") }

  scope :name_ordered, -> {order(name: :asc)}
  scope :by_region, ->(region) { where region: region }
  scope :by_status, ->(s_stat) { where s_stat: s_stat }
=begin
    scope :jobs_new_to_old, -> { joins("left join (
                                select * from jobs as j where start_date =
                                (select max(start_date) from jobs where store_code = j.store_code LIMIT 1))
                                as jobss on jobss.store_code = stores.code").where('jobss.user_id=13').order('FIELD(jobss.status_id,4,3,1,2,5) desc','jobss.start_date desc') }

  #order('jobss.status_id desc','jobss.start_date desc')
=end
  scope :jobs_new_to_old, #-> { joins("left join (
                          #      select * from jobs as j where start_date =
                          #      (select max(start_date) from jobs where store_code = j.store_code LIMIT 1))
                          #       as jobss on jobss.store_code = stores.code").order('FIELD(jobss.status_id,4,3,1,2,5) desc','jobss.start_date desc') }
        -> { joins("left join jobs on jobs.store_code = stores.code and jobs.islatest=1").order('FIELD(jobs.status_id,4,3,1,2,5) desc','jobs.start_date desc') }
=begin
        -> { joins("left join (
                                select * from jobs as j where start_date =
                                (select start_date from jobs where store_code = j.store_code order by start_date desc LIMIT 1 ))
                                 as jobss on jobss.store_code = stores.code").order('FIELD(jobss.status_id,4,3,1,2,5) desc','jobss.start_date desc') }
=end

  scope :by_job_date, ->(date_start = nil, date_end = nil) {
    date_start ||= Job.last.start_date
    date_end ||= Time.zone.now
    joins(:jobs).where(jobs: {start_date: date_start..date_end })
  }
  scope :by_user_name, ->(user_name) { joins(:jobs).where(jobs: { user_id: User.find_by(username: user_name.downcase).id }) }
  scope :by_user_id, ->(user_id) { where(jobs: { user_id: user_id }) }
  scope :by_job_stat, ->(job_stat_id) { joins(:jobs).where(jobs: {status_id: job_stat_id}) }
  scope :by_job_type, ->(job_type_id) { joins(:jobs).where(jobs: {job_type_id: job_type_id}) }
  has_many :jobs, foreign_key: :store_code

  def rozn
    self.email.split('@').first if self.email
  end
  def pure_name
    name.sub("м-н", "").strip
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show]
  before_action :query_params, only: [:index]
  def index
    @stores = Store.all.jobs_new_to_old

    @stores = @stores.by_job_date(params[:date_start], params[:date_end]) if params[:date_start] || params[:date_end]
    #@stores = @stores.by_user_name(params[:user_name]) if params[:user_name] && !params[:user_name].empty?
    @stores = @stores.by_user_id(params[:user_id]) if params[:user_id] && !params[:user_id].empty?
    @stores = @stores.by_job_stat(params[:job_status_id]) if params[:job_status_id] && params[:job_status_id] != "0"
    @stores = @stores.by_job_type(params[:job_type_id]) if params[:job_type_id] && params[:job_type_id] != "0"


    @stores = @stores.by_name(params[:name]) if params[:name] && !params[:name].empty?
    @stores = @stores.by_region(params[:region]) if params[:region] && !params[:region].empty?
    @stores = @stores.by_status(params[:s_stat]) if params[:s_stat] && !params[:s_stat].empty?

    if !params[:s_stat] || params[:s_stat].empty?
      #@stores = @stores.where.not(s_stat: "Закрыт")
    end
    # Hide Тестовый магазин from INDEX page
    # Show it only to user with id 19
    if current_user.id!=19
      @stores = @stores.where.not(name: "м-н Тестовый магазин")
    end

    @stores_filter_status=''
    @stores_filter_status= params[:s_stat] if params[:s_stat] && !params[:s_stat].empty?

    @pagy, @stores = pagy(@stores)
  end

  def main
     if current_user.admin?
       index
       render( 'index')
     else
       user
       render('user')
     end
  end

  def user
    @userid=params[:userid]

    @stores = Store.all.jobs_new_to_old
    @stores = @stores.by_user_id(current_user.id)

    @cnt=@stores.count
    @pagy, @stores = pagy(@stores)
  end

  def show; end

  private

  def set_store
    @store = Store.find(params[:code])
  end
  def query_params
    params.permit(:region, :name, :s_stat, :user_name, :user_id, :date_start, :date_end, :code, :job_status_id, :job_type_id)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
  def regions
    regions = Store.select(:region).distinct
  end

  def status
    status = Store.select(:s_stat).distinct
  end

  def status_select
    select = []
    status.each do |stat|
      select << stat.s_stat
    end
    select << ["Статус", ""]
  end
  def region_select
    select = []
    regions.each do |region|
      select << region.region
    end
    select << ["Регион", ""]
  end

  def job_select
    select = []
    select << ["Ответственный", ""]

    User.all.each do |user|
      select << [user.fullname, user.id]
    end

    #Job.select(:user_id).distinct.each do |job|
      #select << [job.user.fullname, job.user.username]
    #end
    #select << ["Инженер", ""]


    select

  end
end

app/views/stores/_info.html.slim
div.card id="info"
  div.card-header.d-flex
    span.font-weight-bold = @store.name
    span.ml-auto = @store.s_stat
  div.card-body
    P.card-text
      span.font-weight-bold
        ' Код магазина:
      = @store.code
    P.card-text
      span.font-weight-bold
        ' IDD Базы:
      = @store.baseidd
    P.card-text
      span.font-weight-bold
        ' Регион:
      = @store.region
    p.card-text
      span.font-weight-bold
        ' Email:
      = @store.email
    p.card-text
      span.font-weight-bold
        ' Адрес:
      = @store.addr
      p.card-text
        span.font-weight-bold
          ' Время открытия:
        = @store.time_start
      p.card-text
        span.font-weight-bold
          ' Время закрытия:
        = @store.time_end
      p.card-text
        span.font-weight-bold
          ' Часовой пояс:
        = @store.zone
    = link_to "Добавить выезд", new_store_job_path(@store), class: "card-link #{"disabled"}"

app/views/stores/_store.html.slim
- job = store.jobs.first if store.jobs.any?
- color = job ? type_color(job.job_type.name) : ""

- if job
  //- datestr = (job.end_date ? human_date(job.end_date) : human_date(job.start_date).to_s)
  - datestr = (human_date(job.start_date).to_s)
  - jobowner = (current_user.id==job.user.id)

- if job && job.status.id!=3

  div class="card card-index border border-#{ color } rounded-lg"
    div.card-header.bold style="transform: rotate(0);"
      div.d-flex
        span = link_to "#{store.name} (#{store.region})", store_path(store), class: "black without-line stretched-link text-#{color}"
        span.ml-auto = store.s_stat
      div.d-flex
        span.text-muted
          //small = "CODE: #{store.code}"
          = (job.job_type.name)
        span.text-muted.ml-auto
          small = "IDD: #{store.baseidd}"
    div class="card-body"
      p class="card-text"
        = (job.status.name + " " + datestr).capitalize
        - if jobowner
          = ", "
          b = "моя "
        - else
          = ", инженер "
          //= ( (job.end_date ? human_date(job.end_date) : human_date(job.start_date).to_s) + " " + job.status.name ).capitalize + " инженером "
          = link_to job.user.name, user_path(job.user), style: "transform: rotate(0);"

- else

  div class="card card-index border border-#{ color } rounded-lg"
    div.card-header.bold style="padding-bottom:0; border-bottom:none; transform: rotate(0);"
      div.d-flex
        span = link_to "#{store.name} (#{store.region})", store_path(store), class: "black without-line stretched-link text-#{color}"
        span.ml-auto = store.s_stat
      div.d-flex
        span.text-muted
          //small = "CODE: #{store.code}"
          - if job
            = (job.job_type.name)+", "+datestr
          - else
            div style="padding-bottom:12px"
              = "Нет известных работ"

        span.text-muted.ml-auto
          small = "IDD: #{store.baseidd}"
    - if job
      div.card-header.bold style="padding-top:0; border-bottom:none"
        div.d-flex
          span.text-muted.fontsize14
            = "завершено"
            - if jobowner
              b = " мною "
            - else
              = " инженером "
              = link_to job.user.name, user_path(job.user), style: "font-weight: normal;"


br

app/views/stores/index.html.slim
div.row
  div.col-sm-4
  div.col-md

div.row
  div.col-sm-4
    div.sticky-top style="top:5em; padding: 0 0 0 0"
      //- if current_user.id== 19
      div.card.rounded-lg
        div.d-flex.bd-highlight
          div.card-header.flex-md-fill.bd-highlight.text-center
            = link_to "Мои работы", "/works", class: "ml-auto card-link"
          div.card-header.flex-md-fill.bd-highlight.text-center
            span style="text-decoration:overline" Все работы
      br
      div.card.sticky-top.rounded-lg style="top:5em; padding: 0 0 20px 0"
        div.card-header.d-flex
          span Поиск
          //= link_to "Сбросить фильтры", root_path, class: "ml-auto card-link"
          = link_to(image_tag("icon_filter_2.png", class: 'image-responsive ml-auto card-link', style:'width:24px'), "/stores", :title =>"Сбросить фильтры", class: "ml-auto card-link")
        div.card-body
          = form_with(url: "/stores", method: :GET, local: true) do |f|
            div.form-group.card-text
              = f.text_field :name, class: "form-control", placeholder: "Название магазина", value: "#{params[:name] if params[:name]}", oninput: "search_store(this.value)"
              br
              = f.select :s_stat, options_for_select(status_select, "#{params[:s_stat] ? params[:s_stat] : ''}"), {}, {class: "form-control"}
              br
              = f.select :region, options_for_select(region_select, "#{params[:region] ? params[:region] : ''}"), {}, {class: "form-control"}
              br
              = f.select :user_id, options_for_select(job_select, "#{params[:user_id] ? params[:user_id] : ''}"), {}, {class: "form-control"}
              br
              div.input-group
                = f.select :job_status_id, options_for_select(select_options_job_status, (params[:job_status_id] ? params[:job_status_id] : 0)), {}, {class: "form-control"}
                = f.select :job_type_id, options_for_select(select_options_job_type, (params[:job_type_id] ? params[:job_type_id] : 0)), {}, {class: "form-control"}
              br
              = f.submit value: "Показать", class: "btn btn-outline-primary", style: "width:100%;margin:auto" , data: {disable_with: "Поиск"}
  div.col-md data-target="stores-index-wrapper"


    == render partial: 'store', collection: @stores, cached: true

    - if @pagy.count< 1
      div.text-center
        ' По указанным критериям поиска работы не найдены.
        br
          ' Попробуйте изменить запрос...
        br
    -if @pagy.pages>1
      == pagy_bootstrap_nav(@pagy)
    div style="text-align:center"
      div style="padding-bottom:20px"
        b
          'Найдено магазинов:
        b
          ==@pagy.count
        - if !@stores_filter_status.empty?
          '  (#{@stores_filter_status.downcase})



javascript:
  $(function () {
     $('#searchByName').on('input', function (event) {
         var href = $('#submitSearch').attr('href');
         href = href.replace(new RegExp("name=[^&]{0,}"), "name=" + event.target.value);
         $('#submitSearch').attr('href', href);
     }).keypress(function (event) {
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if (keycode == '13'){
            var url = $('#submitSearch').attr('href');
            document.location = url
        }
     });
  });

app/views/stores/index.js.erb
$('div[data-target="stores-index-wrapper"]').html(
    `<%= 'ddfd'
    render partial: 'store', collection: @stores

    if  @stores.count< 1
       ' div.text-center
         По указанным критериям поиска работы не найдены.
         br
          Попробуйте изменить запрос...
        br '
    end
    'ddfd'
    if @stores.count>1

    'div style="text-align:center"
      div style="padding-bottom:20px"
        b
          Найдено магазинов:
        b'
         @stores.count
     end

    %>`
)

app/views/stores/show.html.slim
div.row
  div.col-sm-4
    div.sticky-top style="top:5em"
      == render 'info'
  div.col-md
    - @store.jobs.each do |job|
      - color = type_color(job.job_type.name)
      div class="card card-index rounded-lg border border-#{ color }"
        div.card-header.d-flex.bold style="transform: rotate(0)"
          span
            //= link_to "#{job.job_type.name} от #{ human_date(job.end_date ? job.end_date : job.start_date) }", store_job_path(@store.code, job), class: "without-line stretched-link text-#{ color }"
            = link_to "#{job.job_type.name} от #{ human_date(job.start_date) }", store_job_path(@store.code, job), class: "without-line stretched-link text-#{ color }"
          span.ml-auto
            = job.status.name
        div.card-body
          p.card-text = link_to job.user.name, user_path(job.user) if job.user
      br

app/views/stores/storelist.html.slim
div.row
  div.col-sm-4
  div.col-md



div.row
  div.col-sm-4
    div.sticky-top style="top:5em; padding: 0 0 0 0"
      div.card.rounded-lg
        div.d-flex.bd-highlight
          div.card-header.flex-md-fill.bd-highlight.text-center
            //div
              span.fontsize11 style="color:#8950bd" показаны
            //div
            span style="text-decoration:overline" Мои работы
          div.card-header.flex-md-fill.bd-highlight.text-center
            = link_to "Все работы", "/stores", class: "ml-auto card-link"
      br

      div.card.rounded-lg
        div.card-header.d-flex
          span Поиск
          //= link_to "Сбросить фильтры", "/works", class: "ml-auto card-link"
          = link_to(image_tag("icon_filter_2.png", class: 'image-responsive ml-auto card-link', style:'width:24px'), "/works", :title =>"Сбросить фильтры", class: "ml-auto card-link")
          span class="glyphicon glyphicon-align-left" aria-hidden="true"
        div.card-body
          = form_with(url: "/works", method: :GET, local: true) do |f|
            div.form-group.card-text
              = f.text_field :name, class: "form-control", placeholder: "Название магазина", value: "#{params[:name] if params[:name]}", oninput: "search_store(this.value)"
              br
              /= f.text_field :name, class: "form-control", placeholder: "IP", value: "#{params[:name] if params[:name]}", oninput: "search_store(this.value)"
              /br
              /= f.text_field :name, class: "form-control", placeholder: "Телефон", value: "#{params[:name] if params[:name]}", oninput: "search_store(this.value)"
              /br
              = f.select :s_stat, options_for_select(status_select, "#{params[:s_stat] ? params[:s_stat] : ''}"), {}, {class: "form-control"}
              br
              = f.select :region, options_for_select(region_select, "#{params[:region] ? params[:region] : ''}"), {}, {class: "form-control"}
              br
              //= f.select :user_name, options_for_select(job_select, "#{params[:user_name] ? params[:user_name] : ''}"), {}, {class: "form-control"}
              //br
              div.input-group
                = f.select :job_status_id, options_for_select(select_options_job_status, (params[:job_status_id] ? params[:job_status_id] : 0)), {}, {class: "form-control"}
                = f.select :job_type_id, options_for_select(select_options_job_type, (params[:job_type_id] ? params[:job_type_id] : 0)), {}, {class: "form-control"}
              br
              = f.submit value: "Показать", class: "btn btn-outline-primary", style: "width:100%;margin:auto" , data: {disable_with: "Поиск"}
  div.col-md data-target="stores-user-wrapper"
    == render partial: 'store', collection: @stores, cached: true

    -if @pagy.pages>1
      == pagy_bootstrap_nav(@pagy)
    div style="text-align:center"
      div style="padding-bottom:20px"
        'Найдено магазинов:
        ==@stores.count
      ' ghgg
      == @cnt
      ' sss
      ==@stores.size

javascript:
  $(function () {
     $('#searchByName').on('input', function (event) {
         var href = $('#submitSearch').attr('href');
         href = href.replace(new RegExp("name=[^&]{0,}"), "name=" + event.target.value);
         $('#submitSearch').attr('href', href);
     }).keypress(function (event) {
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if (keycode == '13'){
            var url = $('#submitSearch').attr('href');
            document.location = url
        }
     });
  });

app/views/stores/user.html.slim
div.row
  div.col-sm-4
  div.col-md



div.row
  div.col-sm-4
    div.sticky-top style="top:5em; padding: 0 0 0 0"
      div.card.rounded-lg
        div.d-flex.bd-highlight
          div.card-header.flex-md-fill.bd-highlight.text-center
            //div
              span.fontsize11 style="color:#8950bd" показаны
            //div
            span style="text-decoration:overline" Мои работы
          div.card-header.flex-md-fill.bd-highlight.text-center
            = link_to "Все работы", "/stores", class: "ml-auto card-link"
      br

      div.card.rounded-lg
        div.card-header.d-flex
          span Поиск
          //= link_to "Сбросить фильтры", "/works", class: "ml-auto card-link"
          = link_to(image_tag("icon_filter_2.png", class: 'image-responsive ml-auto card-link', style:'width:24px'), "/works", :title =>"Сбросить фильтры", class: "ml-auto card-link")
          span class="glyphicon glyphicon-align-left" aria-hidden="true"
        div.card-body
          = form_with(url: "/works", method: :GET, local: true) do |f|
            div.form-group.card-text
              = f.text_field :name, class: "form-control", placeholder: "Название магазина", value: "#{params[:name] if params[:name]}", oninput: "search_store(this.value)"
              br
              = f.select :s_stat, options_for_select(status_select, "#{params[:s_stat] ? params[:s_stat] : ''}"), {}, {class: "form-control"}
              br
              = f.select :region, options_for_select(region_select, "#{params[:region] ? params[:region] : ''}"), {}, {class: "form-control"}
              br
              //= f.select :user_name, options_for_select(job_select, "#{params[:user_name] ? params[:user_name] : ''}"), {}, {class: "form-control"}
              //br
              div.input-group
                = f.select :job_status_id, options_for_select(select_options_job_status, (params[:job_status_id] ? params[:job_status_id] : 0)), {}, {class: "form-control"}
                = f.select :job_type_id, options_for_select(select_options_job_type, (params[:job_type_id] ? params[:job_type_id] : 0)), {}, {class: "form-control"}
              br
              = f.submit value: "Показать", class: "btn btn-outline-primary", style: "width:100%;margin:auto" , data: {disable_with: "Поиск"}
  div.col-md data-target="stores-user-wrapper"
    == render partial: 'store', collection: @stores, cached: true

    -if @pagy.pages>1
      == pagy_bootstrap_nav(@pagy)
    div style="text-align:center"
      div style="padding-bottom:20px"
        'Найдено магазинов:
        ==@stores.count
      ' ghgg
      == @cnt
      ' sss
      ==@stores.size

javascript:
  $(function () {
     $('#searchByName').on('input', function (event) {
         var href = $('#submitSearch').attr('href');
         href = href.replace(new RegExp("name=[^&]{0,}"), "name=" + event.target.value);
         $('#submitSearch').attr('href', href);
     }).keypress(function (event) {
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if (keycode == '13'){
            var url = $('#submitSearch').attr('href');
            document.location = url
        }
     });
  });

app/views/stores/user.js.erb
$('div[data-target="stores-user-wrapper"]').html(`<%= render partial: 'store', collection: @stores %>`)