config/routes.rb
Rails.application.routes.draw do


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#delete'

  get 'reports/jobs_all' => 'reports#jobs_all'
  get 'photos/:id/check' => 'photos#check'
  get 'works' => 'stores#user'
  put '/events/readall' => 'events#readall'

  #get 'admin/index/task1' => 'admin/#task1'
  #root :to => 'stores#index'
  root :to => 'stores#main'


  resources :user do
    resources :jobs
    resources :events
  end
  resources :stores, param: :code do
    resources :jobs do
      resources :patch_panels do
        resources :ports
      end
      resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
      resources :registrators
    end
  end

  resources :jobs do
    member do
      put 'done'
      put 'accept'
      put 'return_to_work'
      put 'before_done_send_to_admin'
      put 'sn_inc_create'
      put 'sn_inc_delete_link'
      put 'sn_task_create'
      put 'calculate_latest_job_in_store'
      put 'calculate_latest_job_in_store_all'
    end
    resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
    resources :patch_panels do
      resources :ports
    end
    resources :registrators
  end


  namespace :admin do
    get 'index' => 'admin#index'
    resources :staffs
    resources :users
    resources :groupmanager
    resources :settings_ldap
  end

  namespace :info do
    root :to => 'info#index'
    get 'index' => 'info#index'
    get 'category/add' => 'category#add'
    get 'subcategory/add' => 'subcategory#add'
    get 'file/add' => 'file#add'

    get 'category/edit' => 'category#edit'
    get 'subcategory/edit' => 'subcategory#edit'
    get 'file/edit' => 'file#edit'
    get 'file/about' => 'file#about'

    resources :category
    resources :subcategory
    resources :file
  end


    resources :reports
  resources :staff, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  private :id=
  default_scope { includes(:jobs, :user_role, :events) }
  scope :admins_only, -> { where(role_id: 1) }
  scope :exclude_user, -> (user_id) { where.not(id: user_id) }
  scope :search_by_name, -> (name) {where "fullname like (?)", "%#{name}%"}
  scope :search_by_id, -> (user_id) {where(id: user_id)}
  scope :supervisers, -> {where supervisor: true}
  belongs_to :user_role, foreign_key: :role_id
  has_many :jobs
  has_many :user_default_queries
  has_many :events
  has_many :infos
  has_many :subjobs


  def firstname
    fullname.split.first
  end

  def name_short
    orig_name=name
    arr=orig_name.split(' ')

    if arr.size==3
      name_short=arr[0]+' '+arr[1].slice(0,1).capitalize+'. '+arr[2].slice(0,1).capitalize+'. '
    else
      name_short=orig_name
    end

  end

  def name
    name_reg = %r"\((.*?)\)"
    match = self.fullname.match name_reg
    if match
      name = match.captures.first
    else
      name = self.fullname.split.first
    end
  end

  def admin?
    case self.user_role.role
    when 'Admin'
      true
    when 'User'
      false
    else
      false
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class Admin::UsersController < AdminController
    before_action :admin?, except: [:index]
    before_action :set_user, only: [:update, :edit]
    def index
      @users = User.all
      @users = @users.search_by_name(params[:search]) if params[:search] && !params[:search].empty?
      respond_to do |format|
        format.js
        format.html
      end
    end
    def new
      @user = User.new
      respond_to do |format|
        format.js
        format.html
      end
    end

    def create
      @user = User.new(user_params)
      if @user.save
        respond_to do |format|
          format.js
          format.html
        end
      end
    end

    def edit; end

    def update
      if @user.update(user_params)
        respond_to do |format|
          format.js
          format.html
        end
      end
    end

    private
    def user_params
      params.require(:user).permit(:username, :email, :fullname, :role_id, :supervisor, :password, :flocal)
    end
    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :user_params, only: [:create, :update]
  before_action :set_user, only: [:show, :edit, :update]
  def index
    @users = User.all
  end

  def show; end



  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user_helper.rb
module UserHelper
  def user_exist?(username)
    User.find_by_username(username.downcase)
  end

  def user_select
    select = []
    User.all.each do |user|
      select << [user.fullname, user.id]
    end
    select
  end




end

app/views/user/index.html.slim
div.card-columns style="column-count: 5"
  - @users.each do |user|
    div.card.card-index style="transform: rotate(0)"
      div.card-header
        = link_to user.name, user_path(user), class: "without-line stretched-link"
      div.card-body
        -if user.jobs.any?
          div.card-text
            | Работ: #{user.jobs.count}
          div.card-text
            - Status.all.each do |status|
              ul
                li
                  '#{status.name}: #{user.jobs.where(status_id: status.id).count}
                  - JobType.all.each do |job_type|
                    ul
                      li
                        '#{job_type.name}: #{user.jobs.where(status_id: status.id, job_type_id: job_type.id).count}
        - else
          p.card-text
            | Этот пользователь не совершил ни одной работы

app/views/user/show.html.slim
div.row
  div.col-sm-4
    div.card.rounded-lg.sticky-top style="top:5em; padding: 0 0 20px 0"
      div.card-header.d-flex
        span.font-weight-bold
          = @user.name
        span.left-flex
          = @user.user_role.role
      div.card-body
        p.card-text
          span.font-weight-bold
            ' Email:
          span = @user.email
        p.card-text
          span.font-weight-bold
            ' Кол-во работ:
          span = @user.jobs.count
        = link_to "Настройка", admin_index_path, class: "card-link" if current_user.admin? && current_user.id == @user.id
        = link_to "Отчеты", reports_path, class: "card-link" if current_user.id == @user.id
  div.col-md
    - @user.jobs.each do |job|
      - color = type_color(job.job_type.name)
      div class="card card-index rounded-lg border border-#{ color }"
        div.card-header
          span class="font-weight-bold"
            = link_to "#{job.job_type.name} от #{human_date(job.end_date ? job.end_date : job.start_date)} в #{job.store.name}", job_path(job), class:"stretched-link text-#{ color } without-line"
        div.card-body
          p.card-text
            = job.status.name
      br