config/routes.rb
Rails.application.routes.draw do


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#delete'

  get 'reports/jobs_all' => 'reports#jobs_all'
  get 'photos/:id/check' => 'photos#check'
  get 'works' => 'stores#user'
  put '/events/readall' => 'events#readall'

  #get 'admin/index/task1' => 'admin/#task1'
  #root :to => 'stores#index'
  root :to => 'stores#main'


  resources :user do
    resources :jobs
    resources :events
  end
  resources :stores, param: :code do
    resources :jobs do
      resources :patch_panels do
        resources :ports
      end
      resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
      resources :registrators
    end
  end

  resources :jobs do
    member do
      put 'done'
      put 'accept'
      put 'return_to_work'
      put 'before_done_send_to_admin'
      put 'sn_inc_create'
      put 'sn_inc_delete_link'
      put 'sn_task_create'
      put 'calculate_latest_job_in_store'
      put 'calculate_latest_job_in_store_all'
    end
    resources :photos, only: [:show, :edit, :update, :create, :new, :destroy]
    resources :patch_panels do
      resources :ports
    end
    resources :registrators
  end


  namespace :admin do
    get 'index' => 'admin#index'
    resources :staffs
    resources :users
    resources :groupmanager
    resources :settings_ldap
  end

  namespace :info do
    root :to => 'info#index'
    get 'index' => 'info#index'
    get 'category/add' => 'category#add'
    get 'subcategory/add' => 'subcategory#add'
    get 'file/add' => 'file#add'

    get 'category/edit' => 'category#edit'
    get 'subcategory/edit' => 'subcategory#edit'
    get 'file/edit' => 'file#edit'
    get 'file/about' => 'file#about'

    resources :category
    resources :subcategory
    resources :file
  end


    resources :reports
  resources :staff, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/registrator.rb
class Registrator < ApplicationRecord
  belongs_to :job
  has_one :model, class_name: 'Staff', foreign_key: :id, primary_key: :model_id
end

app/controllers/registrators_controller.rb
class RegistratorsController < ApplicationController
  before_action :set_job
  before_action :set_registrator, only: [:edit, :destroy, :update]

  def index; end

  def show; end

  def new
    @registrator = Registrator.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @registrator = Registrator.new(registrator_params)
    if @registrator.save
      respond_to do |format|
        format.js
        format.html
      end
    end
  end

  def edit; end
  def update; end
  def destroy
    @registrator.destroy
    respond_to do |format|
      format.js
      format.html
    end
  end
  private

  def set_job
    @job = Job.find(params[:job_id])
    @store = @job.store
  end

  def set_registrator
    @registrator = Registrator.find(params[:id])
  end
  def registrator_params
    params.require(:registrator).permit(:job_id, :model_id, :cum_count, :ip_address )
  end
end

app/helpers/registrators_helper.rb
module RegistratorsHelper
  def select_registrators
    select = []
    Staff.all.where(staff_type: 2).each do |staff|
      select << [staff.name, staff.id]
    end
    select
  end
end

app/views/registrators/_form.html.slim
= form_with(model: @registrator, url: [@store, @job, @registrator]) do |f|
  = f.hidden_field :job_id, value: @job.id
  div.form-group
    = f.label :Модель_регистратора
    = f.select :model_id, options_for_select(select_registrators), {}, {class: 'form-control'}
  div.form-group
    = f.label :ip, "IP"
    = f.text_field :ip_address, class: 'form-control'
  div.form-group
    = f.label :Колличество_камер
    = f.select :cum_count, options_for_select(1..16), {}, {class: 'form-control'}
  div.form-group
    = f.submit value: "Сохранить", class: 'btn btn-primary'

app/views/registrators/_registrator.html.slim
div.border.rounded-lg.border-dark id="#{registrator.id}" style="width: max-content; padding: 8px; margin: 8px;"
  p = "Модель: " + registrator.model.name
  p = registrator.cum_count.to_s + " Камер"
  p = "IP: " + registrator.ip_address
  - if current_user.admin?
    // && current_user.id==19
    - passtemp = registrator.ip_address.split(".")[3]
    - passtemp = (passtemp ? passtemp : '20')
    p.verticalmiddle
      ' Pass:
      span id="pass#{registrator.id}" = "rozn@" +(@job.store.baseidd.to_i).to_s + "06" + passtemp.to_s
      //input class="btnpasscopy" type="button" title="копировать" data-clipboard-action="copy" data-clipboard-target="pass#{registrator.id}" data-mess-containerID="passMess#{registrator.id}" id="btncopy#{registrator.id}"
        //button class="btn btn-sm btnpasscopy verticalmiddle fontsize11" style=" margin-left:10px; padding:0; border:none; outline:none" type="button" title="копировать" data-clipboard-action="copy" data-clipboard-target="pass#{registrator.id}" data-mess-containerID="passMess#{registrator.id}" id="btncopy#{registrator.id}" копировать
  div.btn-group
    = link_to "Web интерфейс", "http://#{registrator.ip_address}/", target: :_blank, class: 'btn btn-outline-primary border-dark btn-sm', role: 'button'
    - if current_user.admin? || (current_user.id == registrator.job.user.id && registrator.job.status.id.in?([2,5]))
      = link_to "Удалить", job_registrator_path(registrator.job.id, registrator.id), :method => :delete, :remote => true, data: {confirm: "Вы уверены что хотите удалить видеорегистратор?"}, class: 'btn btn-outline-danger btn-sm btn-r border-dark ml-auto', role: 'button'


css:
  .btn-l {
    border-right: none;
  }

  .btn-r {
    border-left: none;
  }

//script src="/app/assets/javascripts/clipboardjs/clipboard.min.js"

app/views/registrators/create.js.erb
$('#registrators-wrapper').append(`<%= render partial: 'registrator', locals: {registrator: @registrator} %>`);
$('#modalPhoto').modal('hide')
$('#registrator-tab').tab('show');

app/views/registrators/destroy.js.erb
$('div#<%= @registrator.id %>').remove();

app/views/registrators/index.html.slim
h1 Hello from #{@store.name}

app/views/registrators/new.js.erb
$('#photoModalBody').html(`<%= render 'form' %>`);
$('#photoTitleModal').html('<h5> Добавить видеорегистратор</h5>')
$('#modalPhoto').modal('show');